---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>",
    fig.path = "man/figures/README-",
    out.width = "100%"
)
```

# startifyR

<!-- badges: start -->
<!-- badges: end -->

startifyR is similar to [cowsay](https://github.com/sckott/cowsay), just with different quotes and ascii art.  
Inspired by [startify](https://blog.merlinsbeard.ai/how-to-show-an-ascii-art-welcome-screen-at-the-top-of-the-vim-terminal/).

## Installation

You can install the development version of startifyR from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("schochastics/startifyR")
```

## Example

```{r example}
library(startifyR)
set.seed(12345)
startify()
```

```{r example2}
startify()
```

If you want to have a different quote everytime you start an R console, put
```r
if (interactive()) {
    startifyR::startify()
}
```

in `~/.Rprofile`.